### ISSUE TITLE
Problem with the library on my wipy

### ISSUE THREAD

**Issue by Ryuuzan** [wendlers/micropython-mfrc522#3]
Hi,
I'm trying to use the library on my wipy, the code seems to run because it prints
"Place card before reader to read from address 0x08")
However it looks like the RFID card isn't detected, Am I the only one?
I'm using the code with some modification on the pin because they're called G17 and not GP17

**Comment by cefn** [comment]
See https://github.com/wendlers/micropython-mfrc522/issues/2#issuecomment-308055030 which suggests how to report an issue. Then come back here and provide more detail if you would like to progress the issue.

I am working with ESP8266, Micropython and MFRC522 but from your report I am unable to understand what wiring you have made or what software you are running. For example are you following the README instructions and running read.do_read()? What happens?  

Neither G17 or GP17 are referred to in the README. If you have modified the code, please share the modified code, or preferably just use the reference code provided as per the README and wire it following the chart.
